# Generated by Django 4.0.2 on 2022-05-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_image'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
