# Generated by Django 4.0.2 on 2022-05-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0004_alter_shopkeeper_user'),
        ('Order', '0003_alter_cartitems_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefrenceID', models.CharField(max_length=25)),
                ('Total', models.FloatField()),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed')], default=(0, 'Pending'), max_length=20)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.product')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.shopkeeper')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Order.order')),
            ],
        ),
    ]
