# Generated by Django 4.0.2 on 2022-05-29 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_order_user_alter_orderitems_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
