# Generated by Django 4.0.2 on 2022-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_rename_oid_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed')], default=(0, 'Pending'), max_length=20),
        ),
    ]
