# Generated by Django 4.0.2 on 2022-05-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_orderitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], default=(0, 'Pending'), max_length=20),
        ),
    ]
