# Generated by Django 4.0.2 on 2022-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_alter_order_refrenceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='ItemRefID',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
