# Generated by Django 4.0.2 on 2022-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_alter_orderitems_itemrefid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'ordering': ['-Created']},
        ),
        migrations.AddField(
            model_name='cartitems',
            name='Created',
            field=models.DateTimeField(default='2022-06-21 01:01'),
            preserve_default=False,
        ),
    ]
