# Generated by Django 4.0.2 on 2022-10-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_alter_cartitems_options_cartitems_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'ordering': ['-Item']},
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='Created',
        ),
    ]
