# Generated by Django 4.0.2 on 2022-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopkeeper',
            old_name='User',
            new_name='User_id',
        ),
    ]
