# Generated by Django 4.0.2 on 2022-05-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_table'),
        ('Shop', '0002_rename_user_shopkeeper_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='User_id',
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
            preserve_default=False,
        ),
    ]
