# Generated by Django 4.0.2 on 2022-05-21 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0003_remove_shopkeeper_user_id_shopkeeper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
