# Generated by Django 4.0.2 on 2022-05-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0004_order_orderitems'),
        ('Shop', '0004_alter_shopkeeper_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefrenceID', models.CharField(max_length=50)),
                ('Total', models.FloatField()),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed')], max_length=25)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_OrderInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('ShopOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shop_order')),
            ],
        ),
    ]
