# Generated by Django 4.0.2 on 2022-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_shop_order_shop_orderinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed')], default=(0, 'Pending'), max_length=25),
        ),
    ]
