# Generated by Django 4.0.2 on 2022-05-29 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0005_alter_order_user_alter_orderitems_item_and_more'),
        ('Shop', '0006_alter_shop_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_orderinventory',
            name='ShopOrder',
        ),
        migrations.AddField(
            model_name='shop_orderinventory',
            name='Buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_orderinventory',
            name='OrderID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_orderinventory',
            name='RefrenceID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_orderinventory',
            name='Seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shop.shopkeeper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_orderinventory',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed')], default=(0, 'Pending'), max_length=25),
        ),
        migrations.DeleteModel(
            name='Shop_Order',
        ),
    ]
