# Generated by Django 4.0.2 on 2022-05-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0004_alter_shopkeeper_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=500)),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(choices=[(0, 'Grains'), (1, 'Masala'), (3, 'Oils'), (4, 'Flour'), (5, 'Eateries'), (6, 'Soap & Detergents'), (7, 'Cosmetics'), (8, 'Others')], max_length=6)),
                ('Qty_Type', models.CharField(choices=[(0, 'Kg'), (1, 'Litre'), (3, 'Piece')], max_length=30)),
                ('Image', models.ImageField(upload_to='product/images')),
                ('Stock', models.IntegerField(default=0)),
                ('Shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.shopkeeper')),
            ],
        ),
    ]
