# Generated by Django 4.0.2 on 2022-05-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.IntegerField(choices=[(0, 'Grains'), (1, 'Masala'), (3, 'Oils'), (4, 'Flour'), (5, 'Eateries'), (6, 'Soap & Detergents'), (7, 'Cosmetics'), (8, 'Others')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Qty_Type',
            field=models.IntegerField(choices=[(0, 'Kg'), (1, 'Litre'), (3, 'Piece')]),
        ),
    ]
