# Generated by Django 4.0.2 on 2022-05-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_category_alter_product_qty_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Shopkeeper',
            new_name='Shop',
        ),
    ]
