# Generated by Django 4.0.2 on 2022-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_shopkeeper_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='product/images/sample.jpeg', upload_to='product/images'),
        ),
    ]
