# Generated by Django 4.0.2 on 2022-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
