# Generated by Django 4.0.2 on 2022-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_mobile_alter_profile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
