# Generated by Django 4.0.2 on 2022-05-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
