# Generated by Django 4.0.2 on 2022-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='User_Type',
            field=models.CharField(choices=[(0, 'Customer'), (1, 'Seller')], max_length=10),
        ),
    ]
